languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
