# http://docs.codeclimate.com/article/296-engines-available-engines
engines:
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - test/**
   - "**.rb"
   - config.ru
   - Gemfile
exclude_paths:
- spec/**/*
- vendor/**/*
- db/schema.rb
