# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

development:
  <<: *default
  database: ccradio_development

test:
  <<: *default
  database: ccradio_test

production:
  <<: *default
  database: ccradio_production
